### ISSUE TITLE
Have you recently squatted the Cortex-R crate name?

### ISSUE THREAD

**Issue by elpiel** [roemvaar/cortex-r#1]
Hello,
I'd like to know if you have any intention in building a low level access crate for the Cortex-R processors?

**Comment by roemvaar** [comment]
Hello, 

I'm currently working on the low-level access crate for Cortex-R processors. 

Feel free to make any suggestions or open a Pull Request with your contributions

**Comment by elpiel** [comment]
Hey, that's great! Support for Cortex-R is something I was looking for.

Did you know that there is a repo for this in rust-embedded?

The crate itself is empty but maybe they would be interested to work on this as well.


https://github.com/rust-embedded/cortex-r

**Comment by roemvaar** [comment]
I didn't know, will definitely check it out next week and try to come up with the best possible solution to provide support for Cortex-R which is the important thing at the end of the day.

Also, I will put out a list of possible features for this crate, will make sure to tag you so you have a chance to check it.

**Comment by elpiel** [comment]
Thank you!
